object Form8: TForm8
  Left = 0
  Top = 0
  Caption = 'TestMessureBandTool'
  ClientHeight = 358
  ClientWidth = 695
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object ChartFrame1: TChartFrame
    Left = 0
    Top = 0
    Width = 695
    Height = 358
    Align = alClient
    AutoScroll = True
    DoubleBuffered = True
    Color = clBtnFace
    ParentBackground = False
    ParentColor = False
    ParentDoubleBuffered = False
    TabOrder = 0
    TabStop = True
    AllowClick = False
    ExplicitLeft = 125
    ExplicitTop = 75
    ExplicitWidth = 570
    ExplicitHeight = 283
  end
  object aOPCTCPSource_V301: TaOPCTCPSource_V30
    RemoteMachine = 'localhost'
    User = #1051#1072#1075#1086#1076#1085#1099#1081
    Password = '314'
    PacketUpdate = True
    Port = 5152
    MainHost = 'localhost'
    MainPort = 5152
    Left = 336
    Top = 112
  end
end
